services:
  - type: web
    name: planning-cavaliers
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
